name: task_management
description: "A new Flutter project."
publish_to: 'none'   
version: 1.0.0+3

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences:  
  easy_localization: ^3.0.7
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.1.2 
  dropdown_button2: ^2.3.9
  dio: ^5.7.0
  fluttertoast: ^8.2.8
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7
  flutter_background_service_ios: ^5.0.3
  syncfusion_flutter_calendar: ^28.1.33
  percent_indicator: ^4.2.4
  linear_progress_bar: ^1.1.2
  google_nav_bar: ^5.0.7
  path_provider: ^2.1.5
  syncfusion_flutter_pdfviewer: ^28.2.3
  path: 
  share_plus: ^10.1.3
  intl: ^0.19.0
  permission_handler: ^11.3.1
  location: ^8.0.0
  google_maps_flutter: ^2.5.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  app_settings: ^5.1.1
  calendar_view: ^1.3.0
  data_table_2: ^2.5.18
  badges: ^3.1.2
  pdf: ^3.11.1
  readmore: 
  pusher_channels_flutter: ^2.5.0
  multi_dropdown: ^3.0.1
  flutter_searchable_dropdown: ^2.0.0
  audioplayers: ^6.1.2
  sqflite: 
  dropdown_search: ^6.0.2
  persistent_bottom_nav_bar_v2: ^5.3.1
  syncfusion_flutter_charts: ^28.2.11
  file_picker: ^9.2.0
  camera: ^0.10.5+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/png/schotest-logo-circle.png" 
  min_sdk_android: 21

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/translations/
    - assets/gif/
    - assets/task_images/
    - assets/mp3/alarm.mp3
    - assets/mp3/emergency_alarm_69780.mp3